name: 'Terraform'

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.3.0

      # Log in to Azure
      - name: 'Log in to Azure'
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDS_PERSONAL }}

      - name: 'Terraform Init'
        run: |
          terraform init -backend-config="storage_account_name=st2wbd00d3o" \
                         -backend-config="container_name=terraformstate" \
                         -backend-config="key=terraform-core.tfstate" \
                         -backend-config="resource_group_name=testlab" \
                         -backend-config="access_key=${{ secrets.AZURE_STORAGE_KEY }}"

      - name: 'Terraform Plan'
        run: terraform plan

      - name: 'Terraform Apply'
        run: terraform apply -auto-approve
